custom: https://ffmpeg.org/donations.html
patreon: johnvansickle
custom: https://www.paypal.me/johnvansickle
custom: bitcoin:13pZjChR1gR6wqzGMuwLAzqeVR5o9XGoCP
custom: https://www.johnvansickle.com/ffmpeg/
